name: Deployment
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Python Requirements
              run: pip install -r requirements.txt
            - name: Test Code
              run: pytest 
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Deply
              run: echo "Deploying to Github.."
