name: Deployment
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout
            - name: Install Python Requirements
              run: pip install -r requirements.txt
            - name: Test Code
              run: pytest 
